version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_rp
    volumes:
      - ./nginx_conf/nginx.conf: /etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - webapp_network
    depends_on:
      webapp
  webapp:
    image: webapp:latest
    ports:
      - 5000
    domainname:
      - webapp
    container_name: webapp
    networks:
      - webapp_network
  networks:
    webapp_network
